Fetch and load data Home Screen
awesome-academy/ios-i-book_lover pull request #9
Opened 2019-04-11 07:22 UTC by khanhnn-1791

### Issue Link :link:

https://edu-redmine.sun-asterisk.vn/issues/9950
### Goals :soccer:

- Fetch data from API and display to the UI
### Implementation Details :construction:

<img width="298" alt="Screen Shot 2019-04-11 at 2 21 34 PM" src="https://user-images.githubusercontent.com/48303238/55938248-27c22d00-5c65-11e9-873c-85492251801c.png">
<img width="310" alt="Screen Shot 2019-04-11 at 2 20 11 PM" src="https://user-images.githubusercontent.com/48303238/55938251-2a248700-5c65-11e9-9d2a-3901870f0d19.png">

2019-04-11 07:24 UTC, khanhnn-1791 commented
ready

2019-04-11 07:30 UTC, thanhlong12312 commented on ios-i-book-lover/Scenes/Home/HomeViewController.swift
> +                    guard let xml = response.result.value else {
gộp cả if let ở dưới cho gọn code

2019-04-11 07:31 UTC, thanhlong12312 commented on ios-i-book-lover/Extensions/UIView+Extension.swift
> +        activityIndicator.center = self.center
dùng thư  viện Then viết cho gọn code

2019-04-11 07:33 UTC, thanhlong12312 commented on ios-i-book-lover/Data/Model/Book/Isbn.swift
> +    var list: [IsbnList]?
tên biến đặt rõ ra nhé

2019-04-11 07:41 UTC, khanhnn-1791 commented on ios-i-book-lover/Data/Model/Book/Isbn.swift
> +    var list: [IsbnList]?
oke a

2019-04-11 07:53 UTC, longvt96 approved these changes

2019-04-11 07:59 UTC, tgdong2296 commented on ios-i-book-lover/Data/Model/Book/Isbn.swift
> +final class IsbnList: Mappable {
mỗi class tách ra 1 file

2019-04-11 07:59 UTC, tgdong2296 commented on ios-i-book-lover/Data/Model/Book/Isbn.swift
> +final class Isbn: Mappable {
tách file

2019-04-11 07:59 UTC, tgdong2296 commented on ios-i-book-lover/Extensions/Date+Extension.swift
> +    func getHalfYearAgo() -> String {
```suggestion
    func getHalfYearAgo() -> Date {
```
như này sẽ hợp lý hơn, khi nào cần string thì gọi hàm toString() bên dưới

2019-04-11 07:59 UTC, tgdong2296 commented on ios-i-book-lover/Extensions/UIView+Extension.swift
> +            $0.frame = CGRect(x: 0, y: 0, width: 50, height: 50)
như này nếu superview có kích thước lớn hơn 50x50 ví dụ như 300x600 chẳng hạn, thì indicator sẽ nằm góc trên bên trái chứ ko nằm giữa

2019-04-11 07:59 UTC, tgdong2296 commented on ios-i-book-lover/Scenes/Cell/BookCell/BookCell.swift
>      @IBOutlet weak var titleLabel: UILabel!
add private cho các outlet

2019-04-11 07:59 UTC, tgdong2296 commented on ios-i-book-lover/Scenes/Home/HomeViewController.swift
> +    private func fetchData(isbn: String, stringUrl: String, cv: UICollectionView) {
việc gọi api request dữ liệu nên để cho 1 class khác quản lý (VD: BookRepository), viewcontroller chỉ gọi hàm trong class đó và lấy kết quả để hiển thị thôi

2019-04-11 08:06 UTC, khanhnn-1791 commented on ios-i-book-lover/Scenes/Home/HomeViewController.swift
> +    private func fetchData(isbn: String, stringUrl: String, cv: UICollectionView) {
Ok để t fix

2019-04-11 08:07 UTC, tienpx3010 commented on ios-i-book-lover/Extensions/UIView+Extension.swift
> +        self.addSubview(backgroundView)
```suggestion
        addSubview(backgroundView)
```

2019-04-11 08:07 UTC, tienpx3010 commented on ios-i-book-lover/Extensions/UIView+Extension.swift
> +        self.isUserInteractionEnabled = true
```suggestion
        isUserInteractionEnabled = true
```

2019-04-11 08:07 UTC, tienpx3010 commented on ios-i-book-lover/Scenes/Home/HomeViewController.swift
> +        Alamofire.request(url, method: .get)
Tách riêng cấu trúc API. Tham khảo: https://github.com/daolq3012/Structure_IOS/tree/mvc_architect/src/Structure_IOS/Data/Source/Remote

2019-04-11 08:07 UTC, tienpx3010 commented on ios-i-book-lover/Scenes/Home/HomeViewController.swift
> +        fetchIsbn(stringUrl: "\(Configuration.popularBookUrl)", cv: popularCollectionView)
Không cần truyền collectionView. Tách riêng thành phần API.

2019-04-11 08:07 UTC, tienpx3010 commented on ios-i-book-lover/Extensions/UIView+Extension.swift
> +    func activityStartAnimating(activityColor: UIColor, backgroundColor: UIColor) {
Bỏ vào extension ViewController

2019-04-11 08:07 UTC, tienpx3010 commented on ios-i-book-lover/Scenes/Cell/BookCell/BookCell.swift
> +            authorLabel.text = book?.author?.name
Thêm func configCell rồi bỏ vào awakeFromNib + guard let thì k cần thực thi các câu lệnh dưới nếu Book = nil

2019-04-11 08:07 UTC, tienpx3010 commented on ios-i-book-lover/Utils/Constants.swift
> +    static let indicatorTag = 475_647
```suggestion
    static let indicatorTag = 999
```

2019-04-11 08:07 UTC, tienpx3010 commented on ios-i-book-lover/Utils/Constants.swift
>      static let heightGenreCell: CGFloat = 67
Bỏ vào struct cell. Tương tự.

2019-04-11 08:07 UTC, tienpx3010 commented on ios-i-book-lover/Service/Configuration.swift
> +    static let list_name = "list-name=hardcover-nonfiction"
```suggestion
    static let nonFictionList = "list-name=hardcover-nonfiction"
```

2019-04-11 09:01 UTC, khanhnn-1791 commented on ios-i-book-lover/Extensions/UIView+Extension.swift
> +    func activityStartAnimating(activityColor: UIColor, backgroundColor: UIColor) {
Em bỏ trong extension để có có thể dùng ở các viewcontroller với cả các cell có chứa view nữa a.

2019-04-12 01:22 UTC, tgdong2296 approved these changes

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Source/Remote/API/Middleware/BaseResult.swift
> +import ObjectMapper
Bỏ

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Data/Model/Isbn/Isbn.swift
> +final class Isbn: Mappable {
```suggestion
final class ISBN: Mappable {
```

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Data/Model/Isbn/Result.swift
> +final class IsbnList: Mappable {
```suggestion
final class ISBNList: Mappable {
```

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Scenes/Cell/BookCell/BookCell.swift
> +        didSet {
Bỏ

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Scenes/Cell/BookCell/BookCell.swift
> +        guard let book = book else {
Bỏ

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Scenes/Cell/BookCell/BookCell.swift
> +        guard let author = book.author,
guard let book = book

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Utils/Cells.swift
> +enum Cells {
Bỏ vào Constants.swift
enum Constants {
          enum Cells
}

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Utils/Cell.swift
> +//  Cell.swift
Bỏ

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Source/Remote/API/Error/ErrorResponse.swift
> +    var message: String?
```suggestion
    var message = ""
```

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Source/Remote/API/Error/ErrorResponse.swift
> +    var documentationUrl: String?
```suggestion
    var documentationUrl = ""
```

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Scenes/Home/HomeViewController.swift
> +            let font = UIFont.systemFont(ofSize: Cells.fontSize)
extension UIFont  {
primary = UIFont
}

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Scenes/Home/HomeViewController.swift
>          }
Căn lề

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Extensions/UIView+Extension.swift
> +            $0.style = UIActivityIndicatorView.Style.gray
```suggestion
            $0.style = .gray
```

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Repository/BookRepository.swift
> +import XMLMapper
Bỏ

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Repository/IsbnRepository.swift
> +import ObjectMapper
Bỏ

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Repository/IsbnRepository.swift
> +    func searchIsbn(published_date: String, completion: @escaping (BaseResultJSON<SearchIsbnResponse>) -> Void) {
```suggestion
    func searchIsbn(publishedDate: String, completion: @escaping (BaseResultJSON<SearchIsbnResponse>) -> Void) {
```

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Scenes/Home/HomeViewController.swift
> +        bookRepository.searchBooks(isbn: isbn) { (result) in
weak self để tránh retain cycle

2019-04-12 01:40 UTC, tienpx3010 commented on ios-i-book-lover/Service/Configuration.swift
> +    static let key = "key=qyFdCI29lON4kCH3G8lQ"
Bỏ api key vào file APIKey.swift rồi add vào gitignore để không đưa lên

2019-04-12 03:08 UTC, tienpx3010 requested changes

2019-04-12 03:08 UTC, tienpx3010 commented on ios-i-book-lover/Scenes/Home/HomeViewController.swift
> +            guard let sSelf = self else {
```suggestion
            guard let self = self else {
```

2019-04-12 03:08 UTC, tienpx3010 commented on ios-i-book-lover/Utils/Constants.swift
>      static let heightGenreCell: CGFloat = 67
Constants.Cells

2019-04-12 03:08 UTC, tienpx3010 commented on ios-i-book-lover/Utils/Cell.swift
> +//  Cell.swift
Thừa file

2019-04-12 04:09 UTC, tienpx3010 approved these changes

2019-04-12 04:09 UTC, merged